package parser

import (
	"fmt"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func stringProductionRuleToStringUpToGenerated(pr ProductionRule[string]) string {
	var outputStringBuilder strings.Builder
	for _, symbol := range pr.Output {
		var outputString string
		switch s := symbol.(type) {
		case Terminal:
			outputString = fmt.Sprintf("Term(%s)", string([]rune{s.Value}))
		case Variable[string]:
			// For autogenerated variables, don't mark the actual name
			if strings.HasPrefix(s.Value, "V") {
				outputString = "Var"
			} else {
				outputString = fmt.Sprintf("Var(%v)", s.Value)
			}
		default:
			panic("Unknown symbol type")
		}
		outputStringBuilder.WriteString(outputString)
	}
	return fmt.Sprintf("%v -> %s", pr.Input, outputStringBuilder.String())
}

func sameStringProductionRulesUpToGenerated(
	prs1 []ProductionRule[string],
	prs2 []ProductionRule[string],
) bool {
	if len(prs1) != len(prs2) {
		return false
	}

	difference := make(map[string]int)

	for _, pr1 := range prs1 {
		difference[stringProductionRuleToStringUpToGenerated(pr1)]++
	}

	for _, pr2 := range prs2 {
		difference[stringProductionRuleToStringUpToGenerated(pr2)]--
	}

	for _, v := range difference {
		if v != 0 {
			return false
		}
	}
	return true
}

var (
	varOffset = 0

	palindromeOrig = NewContextFreeGrammar[string](
		"S", /* start */
		[]ProductionRule[string]{
			{"S", append(append(
				StringToTerminals[string]("a"),
				[]Symbol[string]{Variable[string]{Value: "S"}}...),
				StringToTerminals[string]("a")...)},
			{"S", append(append(
				StringToTerminals[string]("b"),
				[]Symbol[string]{Variable[string]{Value: "S"}}...),
				StringToTerminals[string]("b")...)},
			{"S", StringToTerminals[string]("a")},
			{"S", StringToTerminals[string]("b")},
			{"S", []Symbol[string]{}},
		},
	)

	palindromeAfterStart = NewContextFreeGrammar[string](
		"V0", /* start */
		[]ProductionRule[string]{
			{"S", append(append(
				StringToTerminals[string]("a"),
				[]Symbol[string]{Variable[string]{Value: "S"}}...),
				StringToTerminals[string]("a")...)},
			{"S", append(append(
				StringToTerminals[string]("b"),
				[]Symbol[string]{Variable[string]{Value: "S"}}...),
				StringToTerminals[string]("b")...)},
			{"S", StringToTerminals[string]("a")},
			{"S", StringToTerminals[string]("b")},
			{"S", []Symbol[string]{}},
			{"V0", []Symbol[string]{Variable[string]{Value: "S"}}},
		},
	)

	palindromeAfterTerm = NewContextFreeGrammar[string](
		"V0", /* start */
		[]ProductionRule[string]{
			{"S", []Symbol[string]{
				Variable[string]{Value: "V1"},
				Variable[string]{Value: "S"},
				Variable[string]{Value: "V1"},
			}},
			{"S", []Symbol[string]{
				Variable[string]{Value: "V2"},
				Variable[string]{Value: "S"},
				Variable[string]{Value: "V2"},
			}},
			{"S", StringToTerminals[string]("a")},
			{"S", StringToTerminals[string]("b")},
			{"S", []Symbol[string]{}},
			{"V0", []Symbol[string]{Variable[string]{Value: "S"}}},
			{"V1", StringToTerminals[string]("a")},
			{"V2", StringToTerminals[string]("b")},
		},
	)
)

func generateVariable() string {
	// Increment variable offset to ensure uniqueness
	defer func() { varOffset++ }()
	return fmt.Sprintf("V%d", varOffset)
}

func TestIsInChomskyNormalForm(t *testing.T) {
	assert.False(t, palindromeOrig.IsInChomskyNormalForm())
	assert.False(t, palindromeAfterStart.IsInChomskyNormalForm())
	assert.False(t, palindromeAfterTerm.IsInChomskyNormalForm())
}

func TestApplyCNFStartStep(t *testing.T) {
	g := palindromeOrig.Clone()
	gAfterStart := g.applyCNFStartStep(generateVariable)

	assert.Equal(t, palindromeAfterStart.start, gAfterStart.start)
	assert.True(
		t, 
		sameStringProductionRulesUpToGenerated(palindromeAfterStart.productionRules, gAfterStart.productionRules), 
		fmt.Sprintf("Expected:%+v\nGot:%+v", palindromeAfterStart.productionRules, gAfterStart.productionRules),
	)
}

func TestApplyCNFTermStep(t *testing.T) {
	g := palindromeAfterStart.Clone()
	gAfterTerm := g.applyCNFTermStep(generateVariable)

	assert.Equal(t, palindromeAfterTerm.start, gAfterTerm.start)
	assert.True(
		t,
		sameStringProductionRulesUpToGenerated(palindromeAfterTerm.productionRules, gAfterTerm.productionRules),
		fmt.Sprintf("Expected:%+v\nGot:%+v", palindromeAfterTerm.productionRules, gAfterTerm.productionRules),
	)
}

