package parser

import (
	"fmt"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func varToStringUpToGenerated(v string) string {
	// For autogenerated variables, don't mark the actual name
	if strings.HasPrefix(v, "V") {
		return "Var"
	}
	return fmt.Sprintf("Var(%v)", v)
}

func stringProductionRuleToStringUpToGenerated(pr ProductionRule[string]) string {
	var outputStringBuilder strings.Builder
	for _, symbol := range pr.Output {
		var outputString string
		switch s := symbol.(type) {
		case Terminal:
			outputString = fmt.Sprintf("Term(%s)", string([]rune{s.Value}))
		case Variable[string]:
			outputString = varToStringUpToGenerated(s.Value)
		default:
			panic("unreachable")
		}
		outputStringBuilder.WriteString(outputString)
	}
	return fmt.Sprintf("%s -> %s", varToStringUpToGenerated(pr.Input), outputStringBuilder.String())
}

func sameStringProductionRulesUpToGenerated(
	prs1 []ProductionRule[string],
	prs2 []ProductionRule[string],
) bool {
	difference := make(map[string]int)

	for _, pr1 := range prs1 {
		difference[stringProductionRuleToStringUpToGenerated(pr1)]++
	}

	for _, pr2 := range prs2 {
		difference[stringProductionRuleToStringUpToGenerated(pr2)]--
	}

	for _, v := range difference {
		if v != 0 {
			return false
		}
	}
	return true
}

var varOffset = 0

func generateVariable() string {
	// Increment variable offset to ensure uniqueness
	defer func() { varOffset++ }()
	return fmt.Sprintf("V%d", varOffset)
}

func TestIsInChomskyNormalForm(t *testing.T) {
	assert.False(t, palindromeOrig.IsInChomskyNormalForm())
	assert.False(t, palindromeAfterStart.IsInChomskyNormalForm())
	assert.False(t, palindromeAfterTerm.IsInChomskyNormalForm())
	assert.False(t, palindromeAfterBin.IsInChomskyNormalForm())
	assert.False(t, palindromeAfterDel.IsInChomskyNormalForm())
	assert.True(t, palindromeAfterUnit.IsInChomskyNormalForm())
}

func TestApplyCNFStartStep(t *testing.T) {
	p := palindromeOrig.Clone()
	pAfterStart := p.applyCNFStartStep(generateVariable)

	assert.Equal(
		t,
		varToStringUpToGenerated(palindromeAfterStart.start),
		varToStringUpToGenerated(pAfterStart.start),
	)
	assert.True(
		t,
		sameStringProductionRulesUpToGenerated(palindromeAfterStart.productionRules, pAfterStart.productionRules),
		fmt.Sprintf("Expected:%+v\nGot:%+v", palindromeAfterStart.productionRules, pAfterStart.productionRules),
	)

	a := arithmeticOrig.Clone()
	aAfterStart := a.applyCNFStartStep(generateVariable)

	assert.Equal(
		t,
		varToStringUpToGenerated(arithmeticAfterStart.start),
		varToStringUpToGenerated(aAfterStart.start),
	)
	assert.True(
		t,
		sameStringProductionRulesUpToGenerated(arithmeticAfterStart.productionRules, aAfterStart.productionRules),
		fmt.Sprintf("Expected:%+v\nGot:%+v", arithmeticAfterStart.productionRules, aAfterStart.productionRules),
	)
}

func TestApplyCNFTermStep(t *testing.T) {
	p := palindromeAfterStart.Clone()
	pAfterTerm := p.applyCNFTermStep(generateVariable)

	assert.Equal(
		t,
		varToStringUpToGenerated(palindromeAfterTerm.start),
		varToStringUpToGenerated(pAfterTerm.start),
	)
	assert.True(
		t,
		sameStringProductionRulesUpToGenerated(palindromeAfterTerm.productionRules, pAfterTerm.productionRules),
		fmt.Sprintf("Expected:%+v\nGot:%+v", palindromeAfterTerm.productionRules, pAfterTerm.productionRules),
	)

	a := arithmeticAfterStart.Clone()
	aAfterTerm := a.applyCNFTermStep(generateVariable)

	assert.Equal(
		t,
		varToStringUpToGenerated(arithmeticAfterTerm.start),
		varToStringUpToGenerated(aAfterTerm.start),
	)
	assert.True(
		t,
		sameStringProductionRulesUpToGenerated(arithmeticAfterTerm.productionRules, aAfterTerm.productionRules),
		fmt.Sprintf("Expected:%+v\nGot:%+v", arithmeticAfterTerm.productionRules, aAfterTerm.productionRules),
	)
}

func TestApplyCNFBinStep(t *testing.T) {
	p := palindromeAfterTerm.Clone()
	pAfterBin := p.applyCNFBinStep(generateVariable)

	assert.True(
		t,
		sameStringProductionRulesUpToGenerated(palindromeAfterBin.productionRules, pAfterBin.productionRules),
		fmt.Sprintf("Expected:%+v\nGot:%+v", palindromeAfterBin.productionRules, pAfterBin.productionRules),
	)

	a := arithmeticAfterTerm.Clone()
	aAfterBin := a.applyCNFBinStep(generateVariable)

	assert.True(
		t,
		sameStringProductionRulesUpToGenerated(arithmeticAfterBin.productionRules, aAfterBin.productionRules),
		fmt.Sprintf("Expected:%+v\nGot:%+v", arithmeticAfterBin.productionRules, aAfterBin.productionRules),
	)
}

func TestApplyCNFDelStep(t *testing.T) {
	p := palindromeAfterBin.Clone()
	pAfterDel, err := p.applyCNFDelStep()
	require.NoError(t, err)

	assert.True(
		t,
		sameStringProductionRulesUpToGenerated(palindromeAfterDel.productionRules, pAfterDel.productionRules),
		fmt.Sprintf("Expected:%+v\nGot:%+v", palindromeAfterDel.productionRules, pAfterDel.productionRules),
	)

	a := arithmeticAfterBin.Clone()
	aAfterDel, err := a.applyCNFDelStep()
	require.NoError(t, err)

	assert.True(
		t,
		sameStringProductionRulesUpToGenerated(arithmeticAfterDel.productionRules, aAfterDel.productionRules),
		fmt.Sprintf("Expected:%+v\nGot:%+v", arithmeticAfterDel.productionRules, aAfterDel.productionRules),
	)
}

func TestApplyCNFUnitStep(t *testing.T) {
	/*
		p := palindromeAfterDel.Clone()
		pAfterUnit := p.applyCNFUnitStep()

		assert.True(
			t,
			sameStringProductionRulesUpToGenerated(palindromeAfterUnit.productionRules, pAfterUnit.productionRules),
			fmt.Sprintf("Expected:%+v\nGot:%+v", palindromeAfterUnit.productionRules, pAfterUnit.productionRules),
		)
	*/

	a := arithmeticAfterDel.Clone()
	aAfterUnit := a.applyCNFUnitStep()

	assert.True(
		t,
		sameStringProductionRulesUpToGenerated(arithmeticAfterUnit.productionRules, aAfterUnit.productionRules),
		fmt.Sprintf("Expected:%+v\nGot:%+v", arithmeticAfterUnit.productionRules, aAfterUnit.productionRules),
	)
}
